/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./components/base-modal/base-modal.vue')['default']
    BlackView: typeof import('./components/black-view/black-view.vue')['default']
    CommonPage: typeof import('./components/common-page/common-page.vue')['default']
    Footer: typeof import('./components/footer/footer.vue')['default']
    InfoCard: typeof import('./components/info-card/info-card.vue')['default']
    MyCalendar: typeof import('./components/my-calendar/my-calendar.vue')['default']
    MyRadio: typeof import('./components/my-radio/my-radio.vue')['default']
    MySwiper: typeof import('./components/my-swiper/my-swiper.vue')['default']
    NavBar: typeof import('./components/nav-bar/nav-bar.vue')['default']
    PageTitle: typeof import('./components/page-title/page-title.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinLoading: typeof import('./components/spin-loading/spin-loading.vue')['default']
    TabBar: typeof import('./components/tab-bar/tab-bar.vue')['default']
  }
}
